trigger: none

pool:
  name: 'Default'

steps:
- task: AzureCLI@2
  displayName: 'Display Resource Group Names Only'
  inputs:
    azureSubscription: 'azure-tfm-sc' 
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './rg-display.sh'