trigger: none

pool:
  name: 'Default'

variables:

- group: 'dev-secrets' 

- name: tf_working_dir
  value: '$(System.DefaultWorkingDirectory)/az-vm-tfm'
- name: service_connection
  value: 'azure-tfm-sc'

stages:


- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    steps:
    - task: TerraformInstaller@1
      inputs: { terraformVersion: 'latest' }

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(tf_working_dir)
        backendServiceArm: $(service_connection)
        backendAzureRmResourceGroupName: 'tfm-tfstate'
        backendAzureRmStorageAccountName: 'azweutfstate'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'vm-deploy.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(tf_working_dir)
        environmentServiceNameAzureRM: $(service_connection)
      env:
        
        TF_VAR_admin_password: $(VM_PASS) 

- stage: Deploy
  displayName: 'Terraform Apply'
  dependsOn: Plan 
  jobs:
  - deployment: TerraformApply
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(tf_working_dir)
              backendServiceArm: $(service_connection)
              backendAzureRmResourceGroupName: 'tfm-tfstate'
              backendAzureRmStorageAccountName: 'azweutfstate'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'vm-deploy.tfstate'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: $(tf_working_dir)
              environmentServiceNameAzureRM: $(service_connection)
            env:
              TF_VAR_admin_password: $(VM_PASS)