trigger: none # This prevents accidental runs

pool:
  name: 'Default' # Your self-hosted agent

variables:
- group: 'dev-secrets' 
- name: tf_working_dir
  value: '$(System.DefaultWorkingDirectory)/az-vm-tfm'

stages:
- stage: DestroyStage
  displayName: 'Terraform Destroy'
  jobs:
  - deployment: TerraformDestroy

    environment: 'dev' 
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self # Required to get your .tf files onto the agent

          - bash: |
              echo "Initializing Terraform..."
              terraform init \
                -backend-config="storage_account_name=azweutfstate" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=vm-deploy.tfstate" \
                -backend-config="resource_group_name=tfm-tfstate"
            displayName: 'Terraform Init'
            workingDirectory: $(tf_working_dir)
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)

          - bash: |
              echo "Starting Destruction..."
              terraform destroy -auto-approve
            displayName: 'Terraform Destroy'
            workingDirectory: $(tf_working_dir)
            env:
              TF_VAR_admin_password: $(VM_PASS)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)